version: '3'

services:
  apache-php:
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    build: ./php
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "52087:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test